version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
    - 21433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sql4dm1n!
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - transport.host=127.0.0.1